### ISSUE TITLE
add -ftabstop=4 as compiler flag

### ISSUE THREAD

**Issue by ekiwi** [roboterclubaachen/xpcc#118]
As this is the standard for our code base, informing the compiler might improve the accuracy of the gcc6 misleading indent warnings.

**Comment by salkinium** [comment]
Or just replace all tabs with spaces. 
🔥 🔥 🔥 

🚒 🚒 🚒

**Comment by salkinium** [comment]
Is this a GCC 6 only flag?

**Comment by ekiwi** [comment]
> Is this a GCC 6 only flag?

might be possible ... gcc has a history of introducing flags just when they are needed instead of ignoring them in older versions, see our history with `-fdiagnostics-color=auto` which killed xpcc for gcc 4.8.

**Comment by ekiwi** [comment]
Let's not add this flag for the moment, as I do not feel like detecting the `gcc` version in order to only provide this flag for the versions which support it.
Let's reopen this issue, once we are actually getting misleading indent warnings.
