### ISSUE TITLE
stm32f1_discovery/board.cfg referencing to non-existing file stm32vldiscovery.cfg

### ISSUE THREAD

**Issue by strongly-typed** [roboterclubaachen/xpcc#121]
In `src/xpcc/architecture/platform/board/stm32f1_discovery/board.cfg`

```
 [openocd]
 configfile = board/stm32vldiscovery.cfg
```

but `stm32vldiscovery.cfg` does not exists.

**Comment by strongly-typed** [comment]
Oh, I see `stm32vldiscovery.cfg` is part of `openocd`.

**Comment by salkinium** [comment]
Yes, this makes use of the internal searchpaths of openocd.
Which is really nice, cos this means up-to-date cfgs.
