### ISSUE TITLE
TLSF allocator breaks program

### ISSUE THREAD

**Issue by Sh4rK** [roboterclubaachen/xpcc#136]
Hi!

I updated xpcc to the latest version recently for the I2C fix, but unfortunately my program stopped working properly, nothing is drawn on the screen nor do input buttons work. I used git bisect to find that the breaking commit is 0b457d65525a9ad8f50bd99d8ec961e8ae807c9b, which enables the TLSF allocator, but I don't use dynamic allocation at all. I didn't get to debugging yet (It's just so cumbersome to set up on windows), but from experimenting I suspect something in xpcc, more specifically in formatting (probably floats) might be the cause.

I'll comment when I know more.

**Comment by salkinium** [comment]
I shouldn't have enabled TLFS by default, I'll revert it.

I don't think TLSF is at fault, but the way we configured newlib is the root issue.

**Comment by Sh4rK** [comment]
Manually setting the allocator back to newlib solved the issue, but I still don't know the exact cause, and I don't have time right now to find out :/

**Comment by salkinium** [comment]
I've renabled newlib's allocator for now, since this is too critical to leave be.

This issue stays open until this is properly fixed.
