### ISSUE TITLE
Gmane email list archive is dead

### ISSUE THREAD

**Issue by salkinium** [roboterclubaachen/xpcc#171]
The xpcc mailing list is still available of course, being hosted by the RWTH Aachen University, which also has a [less usable archive here](http://mailman.rwth-aachen.de/pipermail/xpcc-dev/).

We need to update the link in the Readme.

**Comment by ekiwi** [comment]
What are we going to do about that?

It's nice to have our emails archived somewhere accessible to google.
RWTH Aachen has configured their `robot.txt` in a way that blocks google from indexing.

**Comment by salkinium** [comment]
> What are we going to do about that?

"Ingebrigtsen recommends people to have a look at [Mail Archive](http://www.mail-archive.com)."

Example look for the [avr-gcc mailing list](https://www.mail-archive.com/avr-gcc-list@nongnu.org/maillist.html). Not as pretty as Gmane, but it'll do I guess.

**Comment by ekiwi** [comment]
Are you the administrator of our mailing list @salkinium?
If so, could you please [subscribe the Mail Archive](https://www.mail-archive.com/faq.html#newlist) to our list?

**Comment by salkinium** [comment]
I've added the mail archive as a subscriber. There's no page, cos no email has been sent over the list yet.

**Comment by salkinium** [comment]
Oh, never mind, it just works:
https://www.mail-archive.com/xpcc-dev@lists.rwth-aachen.de/
