### ISSUE TITLE
STM32F1 remapping fails with connect method

### ISSUE THREAD

**Issue by strongly-typed** [roboterclubaachen/xpcc#213]
Remapping of pins in our beloved STM32F103 does not work. 

    GpioOutputB9::connect(Can1::Tx, Gpio::OutputType::PushPull);

results in an unchanged `AFIO->MAPR` register.

The cause is that the "Alternate function IO clock" is not enabled. It was considered for [`enableExternalInterrupt()`](https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/architecture/platform/driver/gpio/stm32f1/gpio.hpp.in#L234) but not for normal connect methods. See Reference Manual p113.

It is probably fixed by adding

    RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

in the general startup code.

I will take care of the PR. See you soon.

**Comment by salkinium** [comment]
The clock enable code should be [placed in `gpio_enable.cpp`](https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/architecture/platform/driver/gpio/stm32f1/gpio_enable.cpp.in).

Keep in mind that the F1 AF remapping is completely broken (https://github.com/roboterclubaachen/xpcc/issues/178#issuecomment-250970902). If required for any production code, I recommend setting the AFIO registers manually and ignoring the connect functions. It's shitty, but fixing this is more work.
(Also see the [updated remap data for the F1 series](https://github.com/modm-io/modm-devices/blob/wip/niklas/devices/stm32/stm32f-103-8_b.xml#L109-L294) in modm's device data.)
