### ISSUE TITLE
[stm32f103rg] Device file broken

### ISSUE THREAD

**Issue by strongly-typed** [roboterclubaachen/xpcc#267]
When enabling stm32f103rg in the SConscript.check many warnings of this kind occur:

```
/Users/usr/Dev/2017amt/xpcc_feature_stm32f107/build/release/test/stm32/libxpcc/src/xpcc/architecture/../../../generated_platform/driver/gpio/stm32f1/gpio.hpp:1531:50: warning: left shift count >= width of type [-Wshift-count-overflow]
   AFIO->MAPR = (AFIO->MAPR & ~(1 << 37)) | (0 << 37);
                                                  ^~
```
To me, it suggests that the [device file](https://github.com/roboterclubaachen/xpcc/blob/develop/src/xpcc/architecture/platform/devices/stm32/stm32f103-r_v_z-f_g.xml#L116) is broken.

@salkinium Can you please confirm?

**Comment by salkinium** [comment]
> To me, it suggests that the device file is broken.

It's not a bug, it's a feature! There exists a `MAPR2` register which needs to be used for > bit 31. See [how modm implements this](https://github.com/modm-io/modm/blob/wip/niklas/src/modm/platform/gpio/stm32/connector_specialized.hpp.in#L60):
```c++
%% set reg = "MAPR" if (remap["position"] | int) < 32 else "MAPR2"
AFIO->{{reg}} = (AFIO->{{reg}} & ~({{ remap["mask"] }}UL << {{ (remap["position"] | int) % 32 }})) | (lmb(id) << {{ (remap["position"] | int) % 32 }});
```
