### ISSUE TITLE
Confusing Samples

### ISSUE THREAD

**Issue by Scabber** [roboterclubaachen/xpcc#27]
xpcc/examples/stm32f4_discovery/accelerometer/ main.cpp

// Interrupt lines
typedef GpioInputE0 Int1;
typedef GpioInputE1 Int2;

is declared but never used. Samples should be clean and simple.

**Comment by salkinium** [comment]
Feel free to remove them and commit the result.

Unfortunately it's not enough to limit examples to the bare minimum.
The underlying concepts need to be explained as well.
We are working on it.
