### ISSUE TITLE
Two (Non-) critical warnings

### ISSUE THREAD

**Issue by strongly-typed** [roboterclubaachen/xpcc#271]
There are two warnings in the CI which can be easily fixed (I think)

 * ["XPCC_ISR_NAME" redefined](https://travis-ci.org/roboterclubaachen/xpcc/jobs/257333105#L1874)

 * [void operator delete(void*, size_t)' is a usual (non-placement) deallocation function in C++14 (or with -fsized-deallocation) [-Wc++14-compat]](https://travis-ci.org/roboterclubaachen/xpcc/jobs/257333106#L1136)

**Comment by salkinium** [comment]
> "XPCC_ISR_NAME" redefined

Fixed in #279.
