### ISSUE TITLE
Investigate alternatives for Travis CI

### ISSUE THREAD

**Issue by salkinium** [roboterclubaachen/xpcc#291]
I'm getting very tired of Travis CI, it needs way too much hand holding for something as simple as compiling our code. It's getting ridiculous.

We need to control the environment ourselves and not let Travis yank the rug out of under our feet like with their [latest backwards-incompatible idiocy](https://github.com/roboterclubaachen/xpcc/pull/290).
I want something where we can upload our own Docker container (@strongly-typed already [has](https://github.com/strongly-typed/docker-xpcc-unittest-stm32) [a](https://github.com/strongly-typed/docker-arm-none-eabi-gcc) [few](https://github.com/strongly-typed/docker-xpcc-build-arm) :-).

**Comment by salkinium** [comment]
[CircleCI has first-class support for Docker.](https://circleci.com/features/)

**Comment by salkinium** [comment]
[There's also LambCI](https://medium.com/@hichaelmart/lambci-4c3e29d6599b), but it may be a little too advanced for what we need here.

**Comment by salkinium** [comment]
Ok, I was wrong, it's not Travis CI faults, SCons has been [updated to 3.0.0](http://scons.org/scons-300-is-available.html) and it has support for Python 3.5+. This is pretty exciting!

cc @strongly-typed @dergraaf @ekiwi @daniel-k

**Comment by salkinium** [comment]
Sorry Travis CI, we still love you (somewhat).

**Comment by salkinium** [comment]
I hotfixed this issue in #292.

**Comment by strongly-typed** [comment]
Yeah, really love Docker (who does not?).
Just added to the maybe-someday list. Probably November+ is a good time to set this up, maybe in conjunction with CI-efforts at RCA ;-)

**Comment by strongly-typed** [comment]
So, was too excited about how CircleCI performs, so I just opened #298. Will you merge?

**Comment by salkinium** [comment]
I like opening issues and then magically they get implemented. Very nice!

**Comment by salkinium** [comment]
Fixed by #298.
