### ISSUE TITLE
examples/stm32f4_discoverc/adc interrupt and oversample broken

### ISSUE THREAD

**Issue by daniel-k** [roboterclubaachen/xpcc#31]
Both examples are broken. The matching adc <=> pin is wrong. While fixing this is easy, they get stuck inside `defaultHandler` because `ADC_IRQHandler` is non-existant in compiled binary.

Has this ever worked? I tried to go back in history, but even the initial commit has mixed up matching.

**Comment by salkinium** [comment]
Fixed in f0d485f and 58bf1af.
