### ISSUE TITLE
Python compatibility issues on current dev

### ISSUE THREAD

**Issue by Maju-Ketchup** [roboterclubaachen/xpcc#338]
Since the current dev is 'upgraded' to Python 3, working with Python 2 throws some errors because the 'ConfigParser' class was renamed to 'configparser'.
I have found a small work around to make it backwards compatible while changing one line in one file.

File: compatibility xpcc/scons/site_tools/configfile.py
old code(line 32):
`import configparser`
new code:
```
try:
       import configparser
except:
       import ConfigParser as configparser 
```
Should I commit this small to the current dev for backwards compatibility or should it stay the way it is so everyone should force update to Python 3?

**Comment by salkinium** [comment]
cc @daniel-k @mhthies @strongly-typed

**Comment by mhthies** [comment]
In theory, the build system should work with both, Python 2 and 3 resp. SCons 2.5 and 3.0. I also tested both Python and SCons versions on my computer, before submitting the changes for Python 3 compatibility. That makes me wondering, why the `configparser` import breaks on your system …

**Comment by rleh** [comment]
>In Python 3, [`ConfigParser`](https://docs.python.org/2/library/configparser.html) has been renamed to [`configparser`](https://docs.python.org/3/library/configparser.html) for PEP 8 compliance. [[↗]](https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser)

`import configparser` should fail on all Python 2 installations.
I can reproduce this with Python 2 on my Fedora system:

```
$ python2
Python 2.7.13 (default, Dec  1 2017, 09:21:53) 
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named configparser
```

**Comment by mhthies** [comment]
That lets @Maju-Ketchup's fix seem reasonable to me.

We could discuss if it's more elegant to check for the Python version, instead of catching the import's exception. However, as far as I remember, catching exceptions is "The Pythonic Way"™.

**Comment by chris-durand** [comment]
> I also tested both Python and SCons versions on my computer, before submitting the changes for Python 3 compatibility. That makes me wondering, why the configparser import breaks on your system …

@mhthies You probably installed the python2 configparser backports package from pypi (https://pypi.python.org/pypi/configparser).

**Comment by rleh** [comment]
Python suggests the package [`six` *(Python 2 and 3 compatibility utilities)*](https://pypi.python.org/pypi/six), but this would add an additional dependency.
I like @Maju-Ketchup's solution too.
