### ISSUE TITLE
SoftwareSpiMaster::acquire() is broken

### ISSUE THREAD

**Issue by rleh** [roboterclubaachen/xpcc#357]
Bugfix in modm:
```diff
[...]::acquire(void *ctx, ConfigurationHandler handler)
{
-	if (ctx == nullptr)
+	if (context == nullptr)
```
Code in xpcc:
https://github.com/roboterclubaachen/xpcc/blob/871d2c0dc66a427142ac2076da9f05eda7ef5d89/src/xpcc/architecture/platform/driver/spi/generic/spi_master_impl.hpp#L68-L70

This bug is fixed in modm-io/modm#16

@salkinium Do we want to this fix in xpcc or does that complicate your xpcc-to-modm forward merging after every release?

**Comment by salkinium** [comment]
Yes, if it's simple things that do not

- move files around, or
- modify the template language inside `platform/`,

then it's fine. You can even have duplicate git commits, since I merge it with via content diff patch and not directly.
