### ISSUE TITLE
xpcc::atmega::BufferedUart1

### ISSUE THREAD

**Issue by ghost** [roboterclubaachen/xpcc#4]
Cannot build anything with BufferedUart1

undefined reference to 'xpcc::atmega::BufferedUart1::setBaudrateRegister(unsigned int)'

**Comment by dergraaf** [comment]
Please provide more information for us to be able to help.
What AVR are you using, which compiler and which Git branch?

BufferedUart1 is only available on AVRs that feature at least two UARTs.

**Comment by ghost** [comment]
Sorry for the lack of detail. I am using an atmega644 (2 hardware UARTs),the master git branch. WinAvr avr-g++ compiler.

If I just modify the example usart file (using atmega644 also) to include a BufferedUart1 I can recreate this error.

**Comment by dergraaf** [comment]
The ATMega644 has only one UART. Only the variants ending in P, A or PA have two UARTs. Please check which one you are using. If you select one of these (e.g. "atmega644p") you'll be able to use BufferedUart1.

**Comment by ghost** [comment]
Oh my. Thank you for pointing that out. On a side note. I see that you maintain avr-can-lib as well as xpcc. Which one would you recommend using (MCP2515) Or are they functionally the same.

Thanks again

**Comment by dergraaf** [comment]
They are functionally the same. avr-can-lib is the C version, xpcc has the C++ version.
