### ISSUE TITLE
use fast forward merges for pull requests

### ISSUE THREAD

**Issue by ekiwi** [roboterclubaachen/xpcc#54]
I just had a look at the recent `xpcc` history and I find it much less readable than in used to be.
For every commit that actually contains an improvement we now get another merge commit, that does not really contain much information on top of the commit that was merged.

To do fast forward merges we would have to merge manually without using githubs built in merge button, but especially for the trivial, single commit pull requests, I would favor this option.

Some links:
- http://blog.differential.com/best-way-to-merge-a-github-pull-request/
- https://github.com/gushphp/gush/issues/372
- https://github.com/wp-e-commerce/wp-e-commerce/wiki/Merging-Pull-Requests
- https://help.github.com/articles/merging-a-pull-request/

**Comment by salkinium** [comment]
Ok, sounds very reasonable, let's do it that way.
