### ISSUE TITLE
Compilation failure on Ubuntu 13.10

### ISSUE THREAD

**Issue by mgajda** [roboterclubaachen/xpcc#8]
Hi,

I just followed your guide, and got the following error when trying to compile xpcc:

Compiling C++: /home/m/src/xpcc/build/unittest_hosted/libxpcc/src/xpcc/workflow/rtos/boost/mutex.o
In file included from xpcc/workflow/rtos/boost/../mutex.hpp:37:0,
                 from xpcc/workflow/rtos/boost/mutex.cpp:31:
xpcc/workflow/rtos/boost/../boost/mutex.hpp:95:39: error: expected template-name before ‘<’ token
   class MutexGuard : boost::lock_guardboost::timed_mutex
                                       ^
xpcc/workflow/rtos/boost/../boost/mutex.hpp:95:39: error: expected ‘{’ before ‘<’ token
xpcc/workflow/rtos/boost/../boost/mutex.hpp:95:39: error: expected unqualified-id before ‘<’ token
xpcc/workflow/rtos/boost/mutex.cpp:48:1: error: expected ‘}’ at end of input
 }
 ^
xpcc/workflow/rtos/boost/mutex.cpp:48:1: error: expected ‘}’ at end of input
scons: **\* [/home/m/src/xpcc/build/unittest_hosted/libxpcc/src/xpcc/workflow/rtos/boost/mutex.o] Error 1
scons: **\* [unittest] Error 2
scons: building terminated because of errors.

Probably wrong boost library version installed by default. The code was straight from your repo. Any suggestions? Which exact versions do you use?
I didn't find any continuous integration link (like Travis), may it be a good source of "known good versions"?

**Comment by ekiwi** [comment]
Hi,

what branch did you use? We normaly work with the develop branch which should thus work with the latest boost version.

Kevin

**Comment by ekiwi** [comment]
Since no one has commented on this for 24 days, I will close this issue for now.
