### ISSUE TITLE
Online documentation is out of date

### ISSUE THREAD

**Issue by rleh** [roboterclubaachen/xpcc#94]
The online documentation at http://xpcc.io/api/modules.html is out of date:

```
Generated on Tue Sep 1 2015 21:39:55 for xpcc by Doxygen
```

**Comment by salkinium** [comment]
I noticed that too, so I generated it two days ago ;-)

```
Generated on Sun Feb 14 2016 16:03:34 for xpcc by Doxygen
```

**Comment by Sh4rK** [comment]
It's a bit messed up though, see the include path here: http://xpcc.io/api/classxpcc_1_1stm32_1_1_clock_control.html

**Comment by salkinium** [comment]
Hm, I'm a bit at war with doxygen. It doesn't deal well with our generated code…
